name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Decode Keystore File
      uses: timheuer/base64-to-file@v1
      id: android_keystore
      with:
       fileName: "android_keystore.keystore"
       encodedString: ${{ secrets.KEYSTORE_FILE }}
 
    - name: Genrate release build 
      run: ./gradlew assembleRelease --stacktrace
      env:
       KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
       STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
       KEY_ALIAS: ${{ secrets.KEY_ALIAS}}
       KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
 
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: app/build/outputs/apk/production/release
